version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  worker:
    image: mher/flower
    entrypoint: celery
    command: -A tasks worker -l info -E
    user: nobody
    volumes:
      - ./src:/data
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
      PYTHONPATH: /data
    depends_on:
      - redis
  flower:
    image: mher/flower
    command: celery -A tasks flower
    volumes:
      - ./src:/data
    working_dir: /data
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - worker
      - redis